/*
 * This source file was generated by the Gradle 'init' task
 */
package taller3;

public class App {

   public static void main(String[] args) {
   

   }

   /*
    * 1. Construya un algoritmo e implemente la función en Java Escribir_asc que
    * reciba tres números enteros diferentes
    * y devuelva en un String en orden ascendente con el siguiente formato:
    * "##### - ##### - #####", donde el primero es
    * el mayor de todos, el segundo el del medio, el tercero el menor de todos. Si
    * hay al menos dos números iguales,
    * devolverá el mensaje: "Error: La función no considera números iguales". Si
    * hay un error inesperado, deberá mostrar
    * el mensaje: "Ocurrió un error inesperado".
    */

   public static String Escribir_asc(int n1, int n2, int n3) {

      try {
         int numero_mayor = 0;
         int numero_medio = 0;
         int numero_menor = 0;

         if (n1 == n2) {
            return "Error: La función no considera números iguales";
         } else if (n1 == n3) {
            return "Error: La función no considera números iguales";
         } else if (n2 == n1) {
            return "Error: La función no considera números iguales";
         } else if (n2 == n3) {
            return "Error: La función no considera números iguales";
         } else if (n3 == n1) {
            return "Error: La función no considera números iguales";
         } else if (n3 == n2) {
            return "Error: La función no considera números iguales";
         }

         if (n1 <= n2 && n1 <= n3) {
            numero_menor = n1;
            if (n2 <= n3) {
               numero_medio = n2;
               numero_mayor = n3;
            } else {
               numero_medio = n3;
               numero_mayor = n2;
            }
         } else if (n2 <= n1 && n2 <= n3) {
            numero_menor = n2;
            if (n1 <= n3) {
               numero_medio = n1;
               numero_mayor = n3;
            } else {
               numero_medio = n3;
               numero_mayor = n1;
            }
         } else {
            numero_menor = n3;
            if (n1 <= n2) {
               numero_medio = n1;
               numero_mayor = n2;
            } else {
               numero_medio = n2;
               numero_mayor = n1;
            }
         }

         return numero_mayor + " - " + numero_medio + " - " + numero_menor;

      }

      catch (Exception e) {
         return "Ocurrió un error inesperado";
      }

   }

   /*
    * 2. Construya un algoritmo e implemente la función en Java Obtener_cifras que
    * recibe un número entre 0 y 50.000
    * y devuelve byte con las cifras que tiene. Por ejemplo 10 tiene dos cifras,
    * 9999 tiene 4 cifras. Si el número
    * no está en el rango devuelve 0. Y si hay un error inesperado, devuelve -1.
    * 
    */

   public static byte Obtener_cifras(int numero) {

      byte cifras = 0;
      final int n_min = 0, n_max = 50000;
      try {

         if (numero < n_min || numero > n_max) {
            return 0;
         }

         String numeroString = String.valueOf(numero);
         cifras = (byte) numeroString.length();
         return cifras;

      } catch (Exception e) {
         return -1;
      }

   }

   /*
    * 3. Construya un algoritmo e implemente la función en Java Clasificar_char que
    * recibe un caracter, y
    * devuelve un string de acuerdo con las siguientes condiciones: si es un
    * alfabético, deuvelve "ES LETRA";
    * si es numérico, devuelve "ES NUMERO" o si es un carácter especial, devuelve
    * "ESPECIAL".
    * Los caracteres se validan de acuerdo con la tabla ascii básica y lo explicado
    * en clase.
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * 
    */

   public static String Clasificar_char(char caracter) {
      try {
         int valorAscii = (int) caracter;

         if ((valorAscii >= 65 && valorAscii <= 90) || (valorAscii >= 97 && valorAscii <= 122)) {
            return "ES LETRA";
         } else if (valorAscii >= 48 && valorAscii <= 57) {
            return "ES NUMERO";
         } else {
            return "ESPECIAL";
         }
      } catch (Exception e) {
         return "Ocurrió un error inesperado: " + e.getMessage();
      }
   }

   /*
    * 
    * 4. Construya un algoritmo e implemente la función en Java
    * Hallar_division_exacta que pida dos números enteros,
    * calcule la división del primero sobre el segundo, y al final si la división
    * es exacta, devuelva "DIVISION EXACTA"
    * y de lo contrario devuelva "DIVISION NO EXACTA". (Exacta significa que tiene
    * cociente, pero no residuo).
    * 
    * Si alguno de los dos números que recibe es cero o negativo, devuelva
    * "NO SE ADMITE CERO O NEGATIVOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * Nota: Revise el funcionamiento del operador mod que le puede ayudar.
    * 
    * 
    * 
    */

   public static String Hallar_division_exacta(int num1, int num2) {

      try {
         String resultado = "";
         int residuo = 0;
         final byte cero = 0;

         if (num1 <= cero || num2 <= cero)
            return "NO SE ADMITE CERO O NEGATIVOS";

         residuo = num1 % num2;

         if (residuo == cero)
            resultado = "DIVISION EXACTA";
         else
            resultado = "DIVISION NO EXACTA";
         return resultado;

      }

      catch (Exception e) {
         return "Ocurrió un error inesperado";
      }

   }

   /*
    * 5. En la siguiente tabla se encuentra la información de las habitaciones de
    * una finca hotel:
    * 
    * Habitación Camas Planta AA/VENTILADOR
    * 101 2 Primera AA /////////
    * 102 1 Primera VE /////////
    * 201 3 Segunda AA /////////
    * 202 2 Segunda VE
    * 301 2 Tercera AA /////////
    * 
    * 
    * Construya un algoritmo e implemente la función en Java Consultar_hab que
    * reciba en un byte el número de camas
    * y en un string si desea VE o AA, y deuvelva en un texto el o los números de
    * habitación que cumplen ese requisito.
    * Si son varias habitaciones, devuelvalas separadas por el caracter |
    * (normalmente, al lado izquierdo de la tecla del 1).
    * Ejemplo: "101|301"
    * Si el número de camas no está entre 1 y 3 o el string es diferente a AA o VE,
    * devuelva "DATOS NO VÁLIDOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    */

   public static String Consultar_hab(byte nro_camas, String clase) {

      try {

         String resultado = "";
         final byte camas_min = 1, camas_max = 3;

         if (nro_camas < camas_min || nro_camas > camas_max || (!clase.equals("AA") && !clase.equals("VE")))
            return "DATOS NO VÁLIDOS";

         switch (nro_camas) {
            case 1:
               if (clase.equals("VE"))
                  resultado = "102";
               break;
            case 2:
               switch (clase) {
                  case "AA":
                     resultado = "101|301";
                     break;
                  case "VE":
                     resultado = "202";
                     break;
               }
               break;
            case 3:
               if (clase.equals("AA"))
                  resultado = "201";
               break;
         }

         return resultado;

      }

      catch (Exception e) {
         return "Ocurrió un error inesperado";
      }

   }

   /*
    * 
    * 6. Un restaurante vende 3 platos. Si el cliente solicita el plato 1, le dan
    * el postre gratis; si selecciona los platos
    * 1 y 2, le dan la bebida gratis y si selecciona los platos 1,2 y 3, le dan
    * postre y bebida.
    * Construya un algoritmo e implemente la función Obtener_obs en Java que reciba
    * 3 booleanos, uno para cada plato y en
    * un String devuelva el obsequio ganado en mayúscula, así: "BEBIDA", "POSTRE",
    * "BEBIDA Y POSTRE".
    * Si los 3 platos vienen en false, , devuelva "PLATOS NO VÁLIDOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    */

   public static String Obtener_obs(boolean plato1, boolean plato2, boolean plato3) {

      try {

         String resultado = "";

         if (plato1 == false && plato2 == false && plato3 == false)
            resultado = "PLATOS NO VÁLIDOS";

         if (plato1 == true && plato2 == false && plato3 == false) {
            resultado = "POSTRE";
         } else if (plato1 == true && plato2 == true && plato3 == false) {
            resultado = "BEBIDA";
         } else if (plato1 == true && plato2 == true && plato3 == true) {
            resultado = "BEBIDA Y POSTRE";
         }

         return resultado;

      }

      catch (Exception e) {
         return "Ocurrió un error inesperado";

      }

   }

   /*
    * 7. Un grupo de amigos hace un sorteo semanalmente con pelotas de ping pong,
    * para saber quién invita y a qué la próxima salida.
    * Las opciones dependen del color que sacan en cada bola y son:
    * 
    * verde: Invita a las cervezas
    * azul: Invita a la pizza
    * rojo: Invita al postre
    * amarillo: Paga el parqueadero de todos
    * blanco o negro: Vaya y disfrute
    * Si la función recibe algo diferente a los colores dados, debe retornar
    * "Error en el color".
    * 
    * Se necesita una función en java Conocer_invitacion que reciba un string con
    * el color de la bola y retorna un
    * String con exactamente el texto de la invitación correspondiente.
    * 
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * 
    */

   public static String Conocer_invitacion(String color) {

      try {

         String resultado = "";

         switch (color) {
            case "verde":
               resultado = "Invita a las cervezas"; 
               break;
            case "azul": 
               resultado = "Invita a la pizza";
               break;
            case "rojo": 
               resultado = "Invita al postre";
               break;
            case "amarillo":
               resultado = "Paga el parqueadero de todos";
               break;
            case "negro": 
               resultado = "Vaya y disfrute";
               break;
            case "blanco": 
               resultado = "Vaya y disfrute";
               break;
            default:
               resultado = "Error en el color";
               break;
         }

         return resultado;

      }

      catch (Exception e) {
         return "Ocurrió un error inesperado";

      }

   }
}
